testData = [
    ['디카페인 아메리카노','./img/drink1/HOT_디카페인 아메리카노.jpg',2500], 
    ['디카페인 카페라떼','./img/drink1/HOT_디카페인 카페라떼.jpg',3900], 
    ['디카페인 바닐라라떼','./img/drink1/HOT_디카페인 바닐라라떼.jpg',4400], 
    ['디카페인 연유라떼','./img/drink1/HOT_디카페인 연유라떼.jpg',4900], 
    ['디카페인 카라멜마끼아또','./img/drink1/HOT_디카페인 카라멜마끼아또.jpg',4700], 
    ['디카페인 카페모카','./img/drink1/HOT_디카페인 카페모카.jpg',4900], 
    ['디카페인 카푸치노','./img/drink1/HOT_디카페인 카푸치노.jpg',3900],
    ['디카페인 아메리카노','./img/drink1/ICE_디카페인 아메리카노.jpg',2500], 
    ['디카페인 카페라떼','./img/drink1/ICE_디카페인 카페라떼.jpg',3900], 
    ['디카페인 바닐라라떼','./img/drink1/ICE_디카페인 바닐라라떼.jpg',4400], 
    ['디카페인 연유라떼','./img/drink1/ICE_디카페인 연유라떼.jpg',4900], 
    ['디카페인 카라멜마끼아또','./img/drink1/ICE_디카페인 카라멜마끼아또.jpg',4700], 
    ['디카페인 카페모카','./img/drink1/ICE_디카페인 카페모카.jpg',4900], 
    ['디카페인 카푸치노','./img/drink1/ICE_디카페인 카푸치노.jpg',3900],
    ['아메리카노','./img/drink1/HOT_아메리카노.jpg',2000],
    ['카페라떼','./img/drink1/HOT_카페라떼.jpg',2900],
    ['바닐라라떼','./img/drink1/HOT_바닐라라떼.jpg',3400],
    ['연유라떼','./img/drink1/HOT_연유라떼.jpg',3900],
    ['카라멜마끼아또','./img/drink1/HOT_카라멜마끼야아또.jpg',3700],
    ['카페모카','./img/drink1/HOT_카페모카.jpg',3900],
    ['카푸치노','./img/drink1/HOT_카푸치노.jpg',2900],
    ['아메리카노','./img/drink1/ICE_아메리카노.jpg',2000],
    ['카페라떼','./img/drink1/ICE_카페라떼.jpg',2900],
    ['바닐라라떼','./img/drink1/ICE_바닐라라떼.jpg',3400],
    ['연유라떼','./img/drink1/ICE_연유라떼.jpg',3900],
    ['카라멜마끼아또','./img/drink1/ICE_카라멜마끼아또.jpg',3500],
    ['카페모카','./img/drink1/ICE_카페모카.jpg',3700],
    ['카푸치노','./img/drink1/ICE_카푸치노.jpg',2700],
    ['복숭아아이스티','./img/drink1/ICE_복숭아아이스티.jpg',3000],
    ['유자차','./img/drink1/ICE_유자차.jpg',3300],
    ['레몬차','./img/drink1/ICE_레몬차.jpg',3300],
    ['자몽차','./img/drink1/ICE_자몽차.jpg',3300],
    ['녹차','./img/drink1/ICE_녹차.jpg',2500],
    ['캐모마일','./img/drink1/ICE_캐모마일.jpg',2500],
    ['얼그레이','./img/drink1/ICE_얼그레이.jpg',2500],
    ['유자차','./img/drink1/HOT_유자차.jpg',3300],
    ['레몬차','./img/drink1/HOT_레몬차.jpg',3300],
    ['자몽차','./img/drink1/HOT_자몽차.jpg',3300],
    ['녹차','./img/drink1/HOT_녹차.jpg',2500],
    ['캐모마일','./img/drink1/HOT_캐모마일.jpg',2500],
    ['얼그레이','./img/drink1/HOT_얼그레이.jpg',2500],
    ['치즈케익','./img/dessert/치즈케익.jpg',3500],
    ['초코케익','./img/dessert/초코케익.jpg',3500],
    ['티라미수케익','./img/dessert/티라미수케익.jpg',3500],
    ['허니브레드','./img/dessert/허니브레드.jpg',4500]
]

#testdata = ['메뉴이름', '이미지경로', '가격']